version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    steps:
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: kenokokoro/php7.4-nginx-buster:0.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: vendor/bin/phpunit -c phpunit.xml --coverage-html=build/coverage-html

      - store_artifacts:
          path: build/coverage-html

      - codecov/upload:
          file: build/coverage-html
